import { config } from "../config.js";
import { logger } from "../engine/logger.js";

const SYSTEM_PROMPT = `You are a risk-focused trading desk supervisor reviewing candidate trade
signals generated by a rule-based technical strategy before they are sent
for execution.

Your job is NOT to be bullish or to chase the signal - it is to act as a
skeptical second opinion. Reject signals that look like chasing momentum
into resistance, that conflict with broader context, or where risk/reward
is poor. Approve only signals you'd be comfortable sizing into.

You MUST respond with ONLY a JSON object (no markdown fences, no prose)
matching exactly this shape:
{
  "approved": boolean,
  "confidence": number,   // 0-1, your confidence in this decision
  "reasoning": string,    // 1-3 sentences
  "sizeAdjustment": number // multiplier 0-1 applied to the position size suggested by risk management (1 = full size, 0.5 = half size, 0 = same as rejecting)
}`;

/**
 * Sends a candidate technical signal to Claude for a secondary review.
 * Returns a conservative default (reject) if the API call fails or the
 * response can't be parsed - the bot should never "fail open" into a trade.
 */
export async function reviewSignal({ symbol, technicalSignal, account, openPositions }) {
  if (!config.claude.apiKey) {
    logger.warn("claudeReview", "No ANTHROPIC_API_KEY set - skipping AI review, rejecting by default");
    return { approved: false, confidence: 0, reasoning: "No Claude API key configured", sizeAdjustment: 0 };
  }

  const userPrompt = `Candidate trade signal:
Symbol: ${symbol}
Action: ${technicalSignal.action}
Technical score: ${technicalSignal.score?.toFixed(2)}
Confidence: ${(technicalSignal.confidence * 100).toFixed(0)}%
Reasons: ${technicalSignal.reasons.join("; ")}
Indicators: ${JSON.stringify(technicalSignal.indicators)}

Account context:
Equity: ${account.equity}
Open positions: ${openPositions.length} (${openPositions.map((p) => p.symbol).join(", ") || "none"})

Should this trade be approved? Respond with the JSON object only.`;

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": config.claude.apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: config.claude.model,
        max_tokens: 300,
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: userPrompt }],
      }),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Claude API error ${res.status}: ${body}`);
    }

    const data = await res.json();
    const text = data.content?.[0]?.text?.trim() ?? "";
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error(`Could not find JSON in Claude response: ${text}`);

    const parsed = JSON.parse(jsonMatch[0]);
    return {
      approved: !!parsed.approved,
      confidence: Number(parsed.confidence) || 0,
      reasoning: String(parsed.reasoning || ""),
      sizeAdjustment: Math.max(0, Math.min(1, Number(parsed.sizeAdjustment) ?? (parsed.approved ? 1 : 0))),
    };
  } catch (err) {
    logger.error("claudeReview", "Review failed, rejecting signal by default", { error: err.message });
    return { approved: false, confidence: 0, reasoning: `Review error: ${err.message}`, sizeAdjustment: 0 };
  }
}
